global using BaseSource.Core.Application.Common.RepositoryPatttern;
global using BaseSource.Core.Domain.Common.Aggregate;
global using BaseSource.Core.Domain.ValueObjects;
global using BaseSource.Core.Infrastrcuture.SQL.Command.Common.DataContext;
global using Microsoft.EntityFrameworkCore; 
global using BaseSource.Core.Application.Common.ServicePattern;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using BaseSource.Core.Infrastrcuture.SQL.Command.DataContext;
